cmake_minimum_required(VERSION 3.18)
project(ksu_cloak CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS_RELEASE "-O2 -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fno-unwind-tables -fno-asynchronous-unwind-tables")
add_library(ksu-cloak SHARED src/module.cpp src/hooks.cpp)
target_include_directories(ksu-cloak PRIVATE src)
target_link_libraries(ksu-cloak log dl)
set_target_properties(ksu-cloak PROPERTIES PREFIX "" OUTPUT_NAME "arm64-v8a")
